---
- name: Add new vlan to vlan database on {{ inventory_hostname }}
  arista.eos.eos_config:
    src: add_vlan.j2

# - name: Saving the running config on {{ inventory_hostname }}
#   arista.eos.eos_config:
#     save_when: always    
