---
all:
  children:
    eos:
      children:
        leafs:
          children:
            vtep1:
              hosts:
                leaf1:
                  ansible_host: 192.168.20.131
                leaf2:
                  ansible_host: 192.168.20.132

            vtep2:
              hosts:
                leaf3:
                  ansible_host: 192.168.20.133
                leaf4:
                  ansible_host: 192.168.20.134
            
            vtep3:
              hosts:
                leaf5:
                  ansible_host: 192.168.20.135
                leaf6:
                  ansible_host: 192.168.20.136

            vtep4:
              hosts:
                leaf7:
                  ansible_host: 192.168.20.137
                leaf8:
                  ansible_host: 192.168.20.138
          vars:
            ansible_network_os: eos
        
        spines:
          hosts:
            spine1:
              ansible_host: 192.168.20.141
            spine2:
              ansible_host: 192.168.20.142
          vars:
            ansible_network_os: eos

###LAB testing
        lab:
          hosts:
            singapore:
              ansible_host: 192.168.20.151
            ashton:
              ansible_host: 192.168.20.152
          vars:
            ansible_network_os: eos

        